# SVG to PNG Converter Configuration - URL-based (Remote Sources)
# Configuration for downloading and converting SVG files from remote URLs

# List of SVG files to process
icons:
  - computer-desktop.svg
  - exclamation-circle.svg
  - bug-ant.svg
  - key.svg
  - video-camera.svg
  - lock-closed.svg
  - shield-check.svg
  - user.svg
  - user-group.svg
  - shield-exclamation.svg
  - bell-alert.svg
  - question-mark-circle.svg

# Sources for different icon types/styles (using remote URLs)
# Each source includes both the path/URL and the suffix for output files
sources:
  - source: "https://raw.githubusercontent.com/tailwindlabs/heroicons/refs/heads/master/optimized/24/outline/"
    suffix: "_outline"
  - source: "https://raw.githubusercontent.com/tailwindlabs/heroicons/refs/heads/master/optimized/24/solid/"
    suffix: "_solid"
  # Add other icon sources as needed:
  # - source: "https://raw.githubusercontent.com/feathericons/feather/master/icons/"
  #   suffix: "_feather"
  # - source: "https://raw.githubusercontent.com/lucide-icons/lucide/main/icons/"
  #   suffix: "_lucide"

# General settings
settings:
  size: 80 # Size for square icons (width and height in pixels)
  color: "#075db3" # Color to apply to icons (hex, named colors, rgb supported)
  outputDirectory: "dist" # Directory where PNG files will be saved
  
  # Wide format settings (16:9 aspect ratio)
  wide:
    width: 320 # Width of wide format
    height: 180 # Height of wide format
    iconSize: 160 # Size of icon in wide format (must be <= min(width, height))
    wideSuffix: "_wide" # Suffix to append to wide format filenames
